version: "3.8"
services:
  laravel:
    build:
      context: ./laravel
    container_name: laravel-container
    ports:
      - "8080:8000"
    networks:
      - laravel-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zabbix
    depends_on:
      - zabbix-db
    networks:
      - laravel-network

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      - ZBX_HOSTNAME=laravel-container
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - laravel-network

  zabbix-db:
    image: postgres:latest
    container_name: zabbix-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zabbix
    networks:
      - laravel-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zabbix
    ports:
      - "8081:8080"
    depends_on:
      - zabbix-server
      - zabbix-db
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
