name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: zabbix
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Install Composer Dependencies
        run: composer install

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run Laravel Tests
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
